# Generated by Django 5.2.13 on 2026-04-25 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "exercises",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("rich_text", "Rich Text"),
                            ("multiple_choice", "Multiple Choice"),
                            ("short_answer", "Short Answer"),
                        ],
                        default="rich_text",
                        max_length=30,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exercises.exercise",
                    ),
                ),
            ],
            options={
                "db_table": "questions",
                "ordering": ["order"],
            },
        ),
    ]
